suppressPackageStartupMessages({library(data.table);library(ggplot2)})
dir.create("manuscript/figures",recursive=TRUE,showWarnings=FALSE)
theme_set(theme_minimal(base_size=12)+theme(panel.grid.minor=element_blank(),plot.title=element_text(face="bold",size=15),plot.subtitle=element_text(size=10),legend.position="bottom"))
annual<-fread("outputs/annual_prevalence.csv")[outcome=="any_barrier" & group=="All survivors"]
adj<-fread("outputs/full/adjusted_annual_prevalence.csv")
a<-rbindlist(list(annual[,.(year,estimate,lower,upper,series="Annual observed")],adj[,.(year,estimate,lower,upper,series="Standardized pooled model")]))
p<-ggplot(a,aes(year,100*estimate,color=series,shape=series,group=series))+geom_line(linewidth=.7)+geom_pointrange(aes(ymin=100*lower,ymax=100*upper),position=position_dodge(width=.18),linewidth=.45)+scale_x_continuous(breaks=2019:2025)+scale_y_continuous(limits=c(0,30),breaks=seq(0,30,5))+scale_color_manual(values=c("Annual observed"="#0b526b","Standardized pooled model"="#b15c21"))+labs(title="Healthcare affordability barriers among stroke survivors",subtitle="National Health Interview Survey 2019-2025",x="Survey year",y="Prevalence (%) with 95% confidence interval",color=NULL,shape=NULL)
ggsave("manuscript/figures/figure1_annual_prevalence.png",p,width=8,height=5,dpi=320,bg="white")
co<-fread("outputs/full/model_coefficients.csv")
want<-data.table(model=c("Age_M3",rep("M3",7)),term=c("young18-64","income_group200-399%","income_group100-199%","income_group<100%","insurancePublic without private","insuranceMilitary only","insuranceUninsured","disabilityWith disability"),label=c("Age 18-64 vs 65+","Income 200-399% vs 400%+ FPL","Income 100-199% vs 400%+ FPL","Income <100% vs 400%+ FPL","Public without private vs private","Military only vs private","Uninsured vs private","Disability vs no disability"),order=1:8)
f<-merge(want,co,by=c("model","term"));f[,label:=factor(label,levels=rev(want$label))]
p<-ggplot(f,aes(PR,label))+geom_vline(xintercept=1,linetype=2,color="gray55")+geom_errorbar(aes(xmin=lower,xmax=upper),orientation="y",width=.15,color="#0b526b")+geom_point(size=2.6,color="#0b526b")+scale_x_log10(breaks=c(.5,1,1.5,2,3,4),limits=c(.45,4))+labs(title="Adjusted associations with affordability barriers",subtitle="Survey-weighted modified Poisson models with ten income imputations",x="Adjusted prevalence ratio with 95% confidence interval",y=NULL)+theme(panel.grid.major.y=element_blank())
ggsave("manuscript/figures/figure2_adjusted_associations.png",p,width=9,height=5.4,dpi=320,bg="white")
# Simple flow figure keeps annual and pooled populations visibly distinct.
nodes<-data.table(x=c(0,0,0,0,0,0),y=c(6,5,4,3,2,1),label=c("207,064 annual Sample Adult records\n2019-2025 full annual files","7,565 records reporting prior stroke\n10 excluded for unknown age","7,555 age-eligible annual stroke records\n7,476 with observed primary outcome","7,181 pooled stroke records\n2020 followback records omitted; partial weights used","7,104 with observed primary outcome\n1,184 report at least one barrier","6,777 in sequential adjusted models\n1,117 report at least one barrier"))
p<-ggplot(nodes,aes(x,y))+geom_label(aes(label=label),size=3.6,lineheight=1.08,fill="#f5f8fa",linewidth=.3,label.padding=grid::unit(.5,"lines"))+annotate("segment",x=0,xend=0,y=c(5.68,4.68,3.68,2.68,1.68),yend=c(5.32,4.32,3.32,2.32,1.32),arrow=grid::arrow(length=grid::unit(.12,"inches")))+coord_cartesian(xlim=c(-1,1),ylim=c(.6,6.4),clip="off")+theme_void()+labs(title="Selection of annual and pooled analytic samples")+theme(plot.title=element_text(hjust=.5,face="bold",size=14))
ggsave("manuscript/figures/figureS1_cohort_flow.png",p,width=7,height=8.4,dpi=250,bg="white")
